const appInfo = {
  TERMINALINFO: {
    top: 100,
    left: 400,
    bottom: 300,
    right: 20,
    width: window.innerWidth - 420,
    height: window.innerHeight - 400,
    isActive: false,
    isShow: false,
    windowName: 'terminal',
    windowBox: null,
    minHeight: 200,
    minWidth: 250,
    zIndex: 0,
    scalable: true
  },
  BROWSERINFO: {
    top: 50,
    left: 200,
    bottom: 100,
    right: 100,
    width: window.innerWidth - 300,
    height: window.innerHeight - 150,
    isActive: false,
    isShow: false,
    windowName: 'browser',
    windowBox: null,
    minHeight: 120,
    minWidth: 250,
    zIndex: 0,
    scalable: true
  },
  BLOBINFO: {
    top: 30,
    left: 100,
    bottom: 200,
    right: 400,
    width: window.innerWidth - 500,
    height: window.innerHeight - 230,
    isActive: false,
    isShow: false,
    windowName: 'blob',
    windowBox: null,
    minHeight: 120,
    minWidth: 250,
    zIndex: 0,
    scalable: true
  },
  WALLPAPERINFO: {
    top: window.innerHeight / 2 - 315,
    left: window.innerWidth / 2 - 400,
    bottom: window.innerHeight / 2 - 315,
    right: window.innerWidth / 2 - 400,
    width: 800,
    height: 630,
    isActive: false,
    isShow: false,
    windowName: 'wallpaper',
    windowBox: null,
    minHeight: 120,
    minWidth: 250,
    zIndex: 0,
    scalable: true
  },
  CHATINFO: {
    top: window.innerHeight / 2 - 315,
    left: window.innerWidth / 2 - 400,
    bottom: window.innerHeight / 2 - 315,
    right: window.innerWidth / 2 - 400,
    width: 800,
    height: 630,
    isActive: false,
    isShow: false,
    windowName: 'chat',
    windowBox: null,
    minHeight: 120,
    minWidth: 250,
    zIndex: 0,
    scalable: true
  }
} as AppInfo

export default appInfo