/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AInputSearch: typeof import('ant-design-vue/es')['InputSearch']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    BlobApp: typeof import('./src/components/WIN-OS/APP/BlobApp.vue')['default']
    Browser: typeof import('./src/components/WIN-OS/APP/Browser.vue')['default']
    Calendar: typeof import('./src/components/WIN-OS/Footer/Calendar.vue')['default']
    ChatApp: typeof import('./src/components/WIN-OS/APP/ChatApp.vue')['default']
    ChatContent: typeof import('./src/components/WIN-OS/APP/ChatApp/ChatContent.vue')['default']
    ChatLogin: typeof import('./src/components/WIN-OS/APP/ChatApp/ChatLogin.vue')['default']
    ChatRoom: typeof import('./src/components/WIN-OS/APP/ChatApp/ChatRoom.vue')['default']
    ColorPicker: typeof import('./src/components/WIN-OS/APP/wallpaperApp/ColorPicker.vue')['default']
    Footer: typeof import('./src/components/WIN-OS/Footer.vue')['default']
    IndexPage: typeof import('./src/components/WIN-OS/APP/Browser/IndexPage.vue')['default']
    Menu: typeof import('./src/components/WIN-OS/Footer/Menu.vue')['default']
    NormalPage: typeof import('./src/components/WIN-OS/APP/Browser/NormalPage.vue')['default']
    PureColor: typeof import('./src/components/WIN-OS/APP/wallpaperApp/pureColor.vue')['default']
    Resizeable: typeof import('./src/components/WIN-OS/Window/Resizeable.vue')['default']
    Terminal: typeof import('./src/components/WIN-OS/APP/Terminal.vue')['default']
    TopPage: typeof import('./src/components/WIN-OS/APP/Browser/TopPage.vue')['default']
    Wallpaper: typeof import('./src/components/WIN-OS/APP/Wallpaper.vue')['default']
    Window: typeof import('./src/components/WIN-OS/Window.vue')['default']
  }
}
